sudo: false
language: python
python:
    - "3.5"
    - "pypy"
    - "pypy-5.3"

install:
    - pip install -r requirements/ci.txt

services:
    - redis-server
    - memcached

script: nosetests tests --with-coverage --with-doctest -v
after_success:
    - coveralls
